/*
 * generated by Xtext 2.25.0
 */
package fr.cs.ontoeventb.pivotmodel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
