/*
 * generated by Xtext 2.25.0
 */
package fr.cs.ontoeventb.pivotmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DSLUiModule extends AbstractDSLUiModule {

	public DSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
