/*
 * generated by Xtext 2.25.0
 */
package fr.cs.ontoeventb.pivotmodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.cs.ontoeventb.pivotmodel.DSLRuntimeModule;
import fr.cs.ontoeventb.pivotmodel.DSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DSLIdeSetup extends DSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DSLRuntimeModule(), new DSLIdeModule()));
	}
	
}
