/*
 * generated by Xtext 2.25.0
 */
package fr.cs.ontoeventb.pivotmodel.ui.tests;

import com.google.inject.Injector;
import fr.cs.ontoeventb.pivotmodel.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("fr.cs.ontoeventb.pivotmodel.DSL");
	}

}
