/*
 * generated by Xtext 2.25.0
 */
package fr.cs.ontoeventb.pivotmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDSLScopeProvider extends DelegatingScopeProvider {
}
