/*
 * generated by Xtext 2.25.0
 */
package fr.cs.ontoeventb.pivotmodel.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/cs/ontoeventb/pivotmodel/parser/antlr/internal/InternalDSL.tokens");
	}
}
