/*
 * generated by Xtext 2.25.0
 */
package fr.cs.ontoeventb.pivotmodel.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.cs.ontoeventb.pivotmodel.ide.contentassist.antlr.internal.InternalDSLParser;
import fr.cs.ontoeventb.pivotmodel.services.DSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class DSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getClassDefinitionAccess().getAlternatives(), "rule__ClassDefinition__Alternatives");
			builder.put(grammarAccess.getPropertyDefinitionAccess().getAlternatives(), "rule__PropertyDefinition__Alternatives");
			builder.put(grammarAccess.getDataTypeDefinitionAccess().getAlternatives(), "rule__DataTypeDefinition__Alternatives");
			builder.put(grammarAccess.getUnitTypeAccess().getAlternatives(), "rule__UnitType__Alternatives");
			builder.put(grammarAccess.getNamedUnitAccess().getAlternatives(), "rule__NamedUnit__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getPredefinedTypeAccess().getAlternatives(), "rule__PredefinedType__Alternatives");
			builder.put(grammarAccess.getPrefixeTypeAccess().getAlternatives(), "rule__PrefixeType__Alternatives");
			builder.put(grammarAccess.getUnitNameAccess().getAlternatives(), "rule__UnitName__Alternatives");
			builder.put(grammarAccess.getPredefinedCurrencyAccess().getAlternatives(), "rule__PredefinedCurrency__Alternatives");
			builder.put(grammarAccess.getPredefinedCollectionAccess().getAlternatives(), "rule__PredefinedCollection__Alternatives");
			builder.put(grammarAccess.getOntologyAccess().getGroup(), "rule__Ontology__Group__0");
			builder.put(grammarAccess.getOntologyAccess().getGroup_4(), "rule__Ontology__Group_4__0");
			builder.put(grammarAccess.getOntologyAccess().getGroup_4_3(), "rule__Ontology__Group_4_3__0");
			builder.put(grammarAccess.getOntologyAccess().getGroup_5(), "rule__Ontology__Group_5__0");
			builder.put(grammarAccess.getOntologyAccess().getGroup_5_3(), "rule__Ontology__Group_5_3__0");
			builder.put(grammarAccess.getOntologyAccess().getGroup_6(), "rule__Ontology__Group_6__0");
			builder.put(grammarAccess.getOntologyAccess().getGroup_6_3(), "rule__Ontology__Group_6_3__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup(), "rule__SimpleClass__Group__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_4(), "rule__SimpleClass__Group_4__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_4_3(), "rule__SimpleClass__Group_4_3__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_5(), "rule__SimpleClass__Group_5__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_5_3(), "rule__SimpleClass__Group_5_3__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_6(), "rule__SimpleClass__Group_6__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_6_3(), "rule__SimpleClass__Group_6_3__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_7(), "rule__SimpleClass__Group_7__0");
			builder.put(grammarAccess.getSimpleClassAccess().getGroup_7_3(), "rule__SimpleClass__Group_7_3__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup(), "rule__CaseOfClass__Group__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_3(), "rule__CaseOfClass__Group_3__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_3_3(), "rule__CaseOfClass__Group_3_3__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_4(), "rule__CaseOfClass__Group_4__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_4_3(), "rule__CaseOfClass__Group_4_3__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_5(), "rule__CaseOfClass__Group_5__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_5_3(), "rule__CaseOfClass__Group_5_3__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_6(), "rule__CaseOfClass__Group_6__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_6_3(), "rule__CaseOfClass__Group_6_3__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_10(), "rule__CaseOfClass__Group_10__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_12(), "rule__CaseOfClass__Group_12__0");
			builder.put(grammarAccess.getCaseOfClassAccess().getGroup_12_3(), "rule__CaseOfClass__Group_12_3__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup(), "rule__UniversalClass__Group__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_3(), "rule__UniversalClass__Group_3__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_3_3(), "rule__UniversalClass__Group_3_3__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_4(), "rule__UniversalClass__Group_4__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_4_3(), "rule__UniversalClass__Group_4_3__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_5(), "rule__UniversalClass__Group_5__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_5_3(), "rule__UniversalClass__Group_5_3__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_6(), "rule__UniversalClass__Group_6__0");
			builder.put(grammarAccess.getUniversalClassAccess().getGroup_6_3(), "rule__UniversalClass__Group_6_3__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup(), "rule__ExistantialClass__Group__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_3(), "rule__ExistantialClass__Group_3__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_3_3(), "rule__ExistantialClass__Group_3_3__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_4(), "rule__ExistantialClass__Group_4__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_4_3(), "rule__ExistantialClass__Group_4_3__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_5(), "rule__ExistantialClass__Group_5__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_5_3(), "rule__ExistantialClass__Group_5_3__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_6(), "rule__ExistantialClass__Group_6__0");
			builder.put(grammarAccess.getExistantialClassAccess().getGroup_6_3(), "rule__ExistantialClass__Group_6_3__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup(), "rule__HasValueClass__Group__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_3(), "rule__HasValueClass__Group_3__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_3_3(), "rule__HasValueClass__Group_3_3__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_4(), "rule__HasValueClass__Group_4__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_4_3(), "rule__HasValueClass__Group_4_3__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_5(), "rule__HasValueClass__Group_5__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_5_3(), "rule__HasValueClass__Group_5_3__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_6(), "rule__HasValueClass__Group_6__0");
			builder.put(grammarAccess.getHasValueClassAccess().getGroup_6_3(), "rule__HasValueClass__Group_6_3__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup(), "rule__MaxCardinalityClass__Group__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_5(), "rule__MaxCardinalityClass__Group_5__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_5_3(), "rule__MaxCardinalityClass__Group_5_3__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_6(), "rule__MaxCardinalityClass__Group_6__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_6_3(), "rule__MaxCardinalityClass__Group_6_3__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_7(), "rule__MaxCardinalityClass__Group_7__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_7_3(), "rule__MaxCardinalityClass__Group_7_3__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_8(), "rule__MaxCardinalityClass__Group_8__0");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getGroup_8_3(), "rule__MaxCardinalityClass__Group_8_3__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup(), "rule__MinCardinalityClass__Group__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_5(), "rule__MinCardinalityClass__Group_5__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_5_3(), "rule__MinCardinalityClass__Group_5_3__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_6(), "rule__MinCardinalityClass__Group_6__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_6_3(), "rule__MinCardinalityClass__Group_6_3__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_7(), "rule__MinCardinalityClass__Group_7__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_7_3(), "rule__MinCardinalityClass__Group_7_3__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_8(), "rule__MinCardinalityClass__Group_8__0");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getGroup_8_3(), "rule__MinCardinalityClass__Group_8_3__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup(), "rule__CardinalityClass__Group__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_5(), "rule__CardinalityClass__Group_5__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_5_3(), "rule__CardinalityClass__Group_5_3__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_6(), "rule__CardinalityClass__Group_6__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_6_3(), "rule__CardinalityClass__Group_6_3__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_7(), "rule__CardinalityClass__Group_7__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_7_3(), "rule__CardinalityClass__Group_7_3__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_8(), "rule__CardinalityClass__Group_8__0");
			builder.put(grammarAccess.getCardinalityClassAccess().getGroup_8_3(), "rule__CardinalityClass__Group_8_3__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup(), "rule__EnumeratedClass__Group__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_3(), "rule__EnumeratedClass__Group_3__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_3_3(), "rule__EnumeratedClass__Group_3_3__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_4(), "rule__EnumeratedClass__Group_4__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_4_3(), "rule__EnumeratedClass__Group_4_3__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_5(), "rule__EnumeratedClass__Group_5__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_5_3(), "rule__EnumeratedClass__Group_5_3__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_6(), "rule__EnumeratedClass__Group_6__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_6_3(), "rule__EnumeratedClass__Group_6_3__0");
			builder.put(grammarAccess.getEnumeratedClassAccess().getGroup_10(), "rule__EnumeratedClass__Group_10__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup(), "rule__UnionClass__Group__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_3(), "rule__UnionClass__Group_3__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_3_3(), "rule__UnionClass__Group_3_3__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_4(), "rule__UnionClass__Group_4__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_4_3(), "rule__UnionClass__Group_4_3__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_5(), "rule__UnionClass__Group_5__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_5_3(), "rule__UnionClass__Group_5_3__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_6(), "rule__UnionClass__Group_6__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_6_3(), "rule__UnionClass__Group_6_3__0");
			builder.put(grammarAccess.getUnionClassAccess().getGroup_10(), "rule__UnionClass__Group_10__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup(), "rule__IntersectionClass__Group__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_3(), "rule__IntersectionClass__Group_3__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_3_3(), "rule__IntersectionClass__Group_3_3__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_4(), "rule__IntersectionClass__Group_4__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_4_3(), "rule__IntersectionClass__Group_4_3__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_5(), "rule__IntersectionClass__Group_5__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_5_3(), "rule__IntersectionClass__Group_5_3__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_6(), "rule__IntersectionClass__Group_6__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_6_3(), "rule__IntersectionClass__Group_6_3__0");
			builder.put(grammarAccess.getIntersectionClassAccess().getGroup_10(), "rule__IntersectionClass__Group_10__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup(), "rule__ComplementClass__Group__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_3(), "rule__ComplementClass__Group_3__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_3_3(), "rule__ComplementClass__Group_3_3__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_4(), "rule__ComplementClass__Group_4__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_4_3(), "rule__ComplementClass__Group_4_3__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_5(), "rule__ComplementClass__Group_5__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_5_3(), "rule__ComplementClass__Group_5_3__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_6(), "rule__ComplementClass__Group_6__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_6_3(), "rule__ComplementClass__Group_6_3__0");
			builder.put(grammarAccess.getComplementClassAccess().getGroup_10(), "rule__ComplementClass__Group_10__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getSingleValueAccess().getGroup(), "rule__SingleValue__Group__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup(), "rule__SimpleProperty__Group__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_8(), "rule__SimpleProperty__Group_8__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_9(), "rule__SimpleProperty__Group_9__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_9_3(), "rule__SimpleProperty__Group_9_3__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_10(), "rule__SimpleProperty__Group_10__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_10_3(), "rule__SimpleProperty__Group_10_3__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_11(), "rule__SimpleProperty__Group_11__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_11_3(), "rule__SimpleProperty__Group_11_3__0");
			builder.put(grammarAccess.getSimplePropertyAccess().getGroup_12(), "rule__SimpleProperty__Group_12__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup(), "rule__ConditionProperty__Group__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_8(), "rule__ConditionProperty__Group_8__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_9(), "rule__ConditionProperty__Group_9__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_9_3(), "rule__ConditionProperty__Group_9_3__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_10(), "rule__ConditionProperty__Group_10__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_10_3(), "rule__ConditionProperty__Group_10_3__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_11(), "rule__ConditionProperty__Group_11__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_11_3(), "rule__ConditionProperty__Group_11_3__0");
			builder.put(grammarAccess.getConditionPropertyAccess().getGroup_12(), "rule__ConditionProperty__Group_12__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup(), "rule__DependentProperty__Group__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_7(), "rule__DependentProperty__Group_7__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_8(), "rule__DependentProperty__Group_8__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_8_3(), "rule__DependentProperty__Group_8_3__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_9(), "rule__DependentProperty__Group_9__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_9_3(), "rule__DependentProperty__Group_9_3__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_10(), "rule__DependentProperty__Group_10__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_10_3(), "rule__DependentProperty__Group_10_3__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_11(), "rule__DependentProperty__Group_11__0");
			builder.put(grammarAccess.getDependentPropertyAccess().getGroup_15(), "rule__DependentProperty__Group_15__0");
			builder.put(grammarAccess.getNotNumericTypeAccess().getGroup(), "rule__NotNumericType__Group__0");
			builder.put(grammarAccess.getNumericType_ImplAccess().getGroup(), "rule__NumericType_Impl__Group__0");
			builder.put(grammarAccess.getMeasureTypeAccess().getGroup(), "rule__MeasureType__Group__0");
			builder.put(grammarAccess.getCurrencyTypeAccess().getGroup(), "rule__CurrencyType__Group__0");
			builder.put(grammarAccess.getClassTypeAccess().getGroup(), "rule__ClassType__Group__0");
			builder.put(grammarAccess.getCollectionTypeAccess().getGroup(), "rule__CollectionType__Group__0");
			builder.put(grammarAccess.getEnumeratedTypeAccess().getGroup(), "rule__EnumeratedType__Group__0");
			builder.put(grammarAccess.getEnumeratedTypeAccess().getGroup_6(), "rule__EnumeratedType__Group_6__0");
			builder.put(grammarAccess.getNumberEnumeratedTypeAccess().getGroup(), "rule__NumberEnumeratedType__Group__0");
			builder.put(grammarAccess.getNumberEnumeratedTypeAccess().getGroup_6(), "rule__NumberEnumeratedType__Group_6__0");
			builder.put(grammarAccess.getNamedUnit_ImplAccess().getGroup(), "rule__NamedUnit_Impl__Group__0");
			builder.put(grammarAccess.getNamedUnit_ImplAccess().getGroup_3(), "rule__NamedUnit_Impl__Group_3__0");
			builder.put(grammarAccess.getDerivedUnitAccess().getGroup(), "rule__DerivedUnit__Group__0");
			builder.put(grammarAccess.getDerivedUnitAccess().getGroup_5(), "rule__DerivedUnit__Group_5__0");
			builder.put(grammarAccess.getNonStandardUnitAccess().getGroup(), "rule__NonStandardUnit__Group__0");
			builder.put(grammarAccess.getNonStandardUnitAccess().getGroup_4(), "rule__NonStandardUnit__Group_4__0");
			builder.put(grammarAccess.getConversionBasedUnitAccess().getGroup(), "rule__ConversionBasedUnit__Group__0");
			builder.put(grammarAccess.getConversionBasedUnitAccess().getGroup_3(), "rule__ConversionBasedUnit__Group_3__0");
			builder.put(grammarAccess.getContextDependentUnitAccess().getGroup(), "rule__ContextDependentUnit__Group__0");
			builder.put(grammarAccess.getContextDependentUnitAccess().getGroup_4(), "rule__ContextDependentUnit__Group_4__0");
			builder.put(grammarAccess.getStandardUnitAccess().getGroup(), "rule__StandardUnit__Group__0");
			builder.put(grammarAccess.getStandardUnitAccess().getGroup_2(), "rule__StandardUnit__Group_2__0");
			builder.put(grammarAccess.getStandardUnitAccess().getGroup_3(), "rule__StandardUnit__Group_3__0");
			builder.put(grammarAccess.getDerivedUnitElementAccess().getGroup(), "rule__DerivedUnitElement__Group__0");
			builder.put(grammarAccess.getDerivedUnitElementAccess().getGroup_3(), "rule__DerivedUnitElement__Group_3__0");
			builder.put(grammarAccess.getOntologyAccess().getNameAssignment_2(), "rule__Ontology__NameAssignment_2");
			builder.put(grammarAccess.getOntologyAccess().getContainedClassesAssignment_4_2(), "rule__Ontology__ContainedClassesAssignment_4_2");
			builder.put(grammarAccess.getOntologyAccess().getContainedClassesAssignment_4_3_1(), "rule__Ontology__ContainedClassesAssignment_4_3_1");
			builder.put(grammarAccess.getOntologyAccess().getContainedPropertiesAssignment_5_2(), "rule__Ontology__ContainedPropertiesAssignment_5_2");
			builder.put(grammarAccess.getOntologyAccess().getContainedPropertiesAssignment_5_3_1(), "rule__Ontology__ContainedPropertiesAssignment_5_3_1");
			builder.put(grammarAccess.getOntologyAccess().getContainedDataTypesAssignment_6_2(), "rule__Ontology__ContainedDataTypesAssignment_6_2");
			builder.put(grammarAccess.getOntologyAccess().getContainedDataTypesAssignment_6_3_1(), "rule__Ontology__ContainedDataTypesAssignment_6_3_1");
			builder.put(grammarAccess.getSimpleClassAccess().getNameAssignment_2(), "rule__SimpleClass__NameAssignment_2");
			builder.put(grammarAccess.getSimpleClassAccess().getSubClassOfAssignment_4_2(), "rule__SimpleClass__SubClassOfAssignment_4_2");
			builder.put(grammarAccess.getSimpleClassAccess().getSubClassOfAssignment_4_3_1(), "rule__SimpleClass__SubClassOfAssignment_4_3_1");
			builder.put(grammarAccess.getSimpleClassAccess().getDisjointWithAssignment_5_2(), "rule__SimpleClass__DisjointWithAssignment_5_2");
			builder.put(grammarAccess.getSimpleClassAccess().getDisjointWithAssignment_5_3_1(), "rule__SimpleClass__DisjointWithAssignment_5_3_1");
			builder.put(grammarAccess.getSimpleClassAccess().getEquivalentToAssignment_6_2(), "rule__SimpleClass__EquivalentToAssignment_6_2");
			builder.put(grammarAccess.getSimpleClassAccess().getEquivalentToAssignment_6_3_1(), "rule__SimpleClass__EquivalentToAssignment_6_3_1");
			builder.put(grammarAccess.getSimpleClassAccess().getDescribedByAssignment_7_2(), "rule__SimpleClass__DescribedByAssignment_7_2");
			builder.put(grammarAccess.getSimpleClassAccess().getDescribedByAssignment_7_3_1(), "rule__SimpleClass__DescribedByAssignment_7_3_1");
			builder.put(grammarAccess.getCaseOfClassAccess().getNameAssignment_1(), "rule__CaseOfClass__NameAssignment_1");
			builder.put(grammarAccess.getCaseOfClassAccess().getSubClassOfAssignment_3_2(), "rule__CaseOfClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getCaseOfClassAccess().getSubClassOfAssignment_3_3_1(), "rule__CaseOfClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getCaseOfClassAccess().getDisjointWithAssignment_4_2(), "rule__CaseOfClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getCaseOfClassAccess().getDisjointWithAssignment_4_3_1(), "rule__CaseOfClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getCaseOfClassAccess().getEquivalentToAssignment_5_2(), "rule__CaseOfClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getCaseOfClassAccess().getEquivalentToAssignment_5_3_1(), "rule__CaseOfClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getCaseOfClassAccess().getDescribedByAssignment_6_2(), "rule__CaseOfClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getCaseOfClassAccess().getDescribedByAssignment_6_3_1(), "rule__CaseOfClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getCaseOfClassAccess().getCaseOfAssignment_9(), "rule__CaseOfClass__CaseOfAssignment_9");
			builder.put(grammarAccess.getCaseOfClassAccess().getCaseOfAssignment_10_1(), "rule__CaseOfClass__CaseOfAssignment_10_1");
			builder.put(grammarAccess.getCaseOfClassAccess().getImportedPropertiesAssignment_12_2(), "rule__CaseOfClass__ImportedPropertiesAssignment_12_2");
			builder.put(grammarAccess.getCaseOfClassAccess().getImportedPropertiesAssignment_12_3_1(), "rule__CaseOfClass__ImportedPropertiesAssignment_12_3_1");
			builder.put(grammarAccess.getUniversalClassAccess().getNameAssignment_1(), "rule__UniversalClass__NameAssignment_1");
			builder.put(grammarAccess.getUniversalClassAccess().getSubClassOfAssignment_3_2(), "rule__UniversalClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getUniversalClassAccess().getSubClassOfAssignment_3_3_1(), "rule__UniversalClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getUniversalClassAccess().getDisjointWithAssignment_4_2(), "rule__UniversalClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getUniversalClassAccess().getDisjointWithAssignment_4_3_1(), "rule__UniversalClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getUniversalClassAccess().getEquivalentToAssignment_5_2(), "rule__UniversalClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getUniversalClassAccess().getEquivalentToAssignment_5_3_1(), "rule__UniversalClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getUniversalClassAccess().getDescribedByAssignment_6_2(), "rule__UniversalClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getUniversalClassAccess().getDescribedByAssignment_6_3_1(), "rule__UniversalClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getUniversalClassAccess().getOnPropertyAssignment_8(), "rule__UniversalClass__OnPropertyAssignment_8");
			builder.put(grammarAccess.getUniversalClassAccess().getToDataDefinitionAssignment_10(), "rule__UniversalClass__ToDataDefinitionAssignment_10");
			builder.put(grammarAccess.getExistantialClassAccess().getNameAssignment_1(), "rule__ExistantialClass__NameAssignment_1");
			builder.put(grammarAccess.getExistantialClassAccess().getSubClassOfAssignment_3_2(), "rule__ExistantialClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getExistantialClassAccess().getSubClassOfAssignment_3_3_1(), "rule__ExistantialClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getExistantialClassAccess().getDisjointWithAssignment_4_2(), "rule__ExistantialClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getExistantialClassAccess().getDisjointWithAssignment_4_3_1(), "rule__ExistantialClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getExistantialClassAccess().getEquivalentToAssignment_5_2(), "rule__ExistantialClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getExistantialClassAccess().getEquivalentToAssignment_5_3_1(), "rule__ExistantialClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getExistantialClassAccess().getDescribedByAssignment_6_2(), "rule__ExistantialClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getExistantialClassAccess().getDescribedByAssignment_6_3_1(), "rule__ExistantialClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getExistantialClassAccess().getOnPropertyAssignment_8(), "rule__ExistantialClass__OnPropertyAssignment_8");
			builder.put(grammarAccess.getExistantialClassAccess().getToDataDefinitionAssignment_10(), "rule__ExistantialClass__ToDataDefinitionAssignment_10");
			builder.put(grammarAccess.getHasValueClassAccess().getNameAssignment_1(), "rule__HasValueClass__NameAssignment_1");
			builder.put(grammarAccess.getHasValueClassAccess().getSubClassOfAssignment_3_2(), "rule__HasValueClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getHasValueClassAccess().getSubClassOfAssignment_3_3_1(), "rule__HasValueClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getHasValueClassAccess().getDisjointWithAssignment_4_2(), "rule__HasValueClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getHasValueClassAccess().getDisjointWithAssignment_4_3_1(), "rule__HasValueClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getHasValueClassAccess().getEquivalentToAssignment_5_2(), "rule__HasValueClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getHasValueClassAccess().getEquivalentToAssignment_5_3_1(), "rule__HasValueClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getHasValueClassAccess().getDescribedByAssignment_6_2(), "rule__HasValueClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getHasValueClassAccess().getDescribedByAssignment_6_3_1(), "rule__HasValueClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getHasValueClassAccess().getOnPropertyAssignment_8(), "rule__HasValueClass__OnPropertyAssignment_8");
			builder.put(grammarAccess.getHasValueClassAccess().getToDataDefinitionAssignment_10(), "rule__HasValueClass__ToDataDefinitionAssignment_10");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getNameAssignment_1(), "rule__MaxCardinalityClass__NameAssignment_1");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getMaxCardAssignment_4(), "rule__MaxCardinalityClass__MaxCardAssignment_4");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getSubClassOfAssignment_5_2(), "rule__MaxCardinalityClass__SubClassOfAssignment_5_2");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getSubClassOfAssignment_5_3_1(), "rule__MaxCardinalityClass__SubClassOfAssignment_5_3_1");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getDisjointWithAssignment_6_2(), "rule__MaxCardinalityClass__DisjointWithAssignment_6_2");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getDisjointWithAssignment_6_3_1(), "rule__MaxCardinalityClass__DisjointWithAssignment_6_3_1");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getEquivalentToAssignment_7_2(), "rule__MaxCardinalityClass__EquivalentToAssignment_7_2");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getEquivalentToAssignment_7_3_1(), "rule__MaxCardinalityClass__EquivalentToAssignment_7_3_1");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getDescribedByAssignment_8_2(), "rule__MaxCardinalityClass__DescribedByAssignment_8_2");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getDescribedByAssignment_8_3_1(), "rule__MaxCardinalityClass__DescribedByAssignment_8_3_1");
			builder.put(grammarAccess.getMaxCardinalityClassAccess().getOnPropertyAssignment_10(), "rule__MaxCardinalityClass__OnPropertyAssignment_10");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getNameAssignment_1(), "rule__MinCardinalityClass__NameAssignment_1");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getMinCardAssignment_4(), "rule__MinCardinalityClass__MinCardAssignment_4");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getSubClassOfAssignment_5_2(), "rule__MinCardinalityClass__SubClassOfAssignment_5_2");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getSubClassOfAssignment_5_3_1(), "rule__MinCardinalityClass__SubClassOfAssignment_5_3_1");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getDisjointWithAssignment_6_2(), "rule__MinCardinalityClass__DisjointWithAssignment_6_2");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getDisjointWithAssignment_6_3_1(), "rule__MinCardinalityClass__DisjointWithAssignment_6_3_1");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getEquivalentToAssignment_7_2(), "rule__MinCardinalityClass__EquivalentToAssignment_7_2");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getEquivalentToAssignment_7_3_1(), "rule__MinCardinalityClass__EquivalentToAssignment_7_3_1");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getDescribedByAssignment_8_2(), "rule__MinCardinalityClass__DescribedByAssignment_8_2");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getDescribedByAssignment_8_3_1(), "rule__MinCardinalityClass__DescribedByAssignment_8_3_1");
			builder.put(grammarAccess.getMinCardinalityClassAccess().getOnPropertyAssignment_10(), "rule__MinCardinalityClass__OnPropertyAssignment_10");
			builder.put(grammarAccess.getCardinalityClassAccess().getNameAssignment_1(), "rule__CardinalityClass__NameAssignment_1");
			builder.put(grammarAccess.getCardinalityClassAccess().getCardAssignment_4(), "rule__CardinalityClass__CardAssignment_4");
			builder.put(grammarAccess.getCardinalityClassAccess().getSubClassOfAssignment_5_2(), "rule__CardinalityClass__SubClassOfAssignment_5_2");
			builder.put(grammarAccess.getCardinalityClassAccess().getSubClassOfAssignment_5_3_1(), "rule__CardinalityClass__SubClassOfAssignment_5_3_1");
			builder.put(grammarAccess.getCardinalityClassAccess().getDisjointWithAssignment_6_2(), "rule__CardinalityClass__DisjointWithAssignment_6_2");
			builder.put(grammarAccess.getCardinalityClassAccess().getDisjointWithAssignment_6_3_1(), "rule__CardinalityClass__DisjointWithAssignment_6_3_1");
			builder.put(grammarAccess.getCardinalityClassAccess().getEquivalentToAssignment_7_2(), "rule__CardinalityClass__EquivalentToAssignment_7_2");
			builder.put(grammarAccess.getCardinalityClassAccess().getEquivalentToAssignment_7_3_1(), "rule__CardinalityClass__EquivalentToAssignment_7_3_1");
			builder.put(grammarAccess.getCardinalityClassAccess().getDescribedByAssignment_8_2(), "rule__CardinalityClass__DescribedByAssignment_8_2");
			builder.put(grammarAccess.getCardinalityClassAccess().getDescribedByAssignment_8_3_1(), "rule__CardinalityClass__DescribedByAssignment_8_3_1");
			builder.put(grammarAccess.getCardinalityClassAccess().getOnPropertyAssignment_10(), "rule__CardinalityClass__OnPropertyAssignment_10");
			builder.put(grammarAccess.getEnumeratedClassAccess().getNameAssignment_1(), "rule__EnumeratedClass__NameAssignment_1");
			builder.put(grammarAccess.getEnumeratedClassAccess().getSubClassOfAssignment_3_2(), "rule__EnumeratedClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getEnumeratedClassAccess().getSubClassOfAssignment_3_3_1(), "rule__EnumeratedClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getEnumeratedClassAccess().getDisjointWithAssignment_4_2(), "rule__EnumeratedClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getEnumeratedClassAccess().getDisjointWithAssignment_4_3_1(), "rule__EnumeratedClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getEnumeratedClassAccess().getEquivalentToAssignment_5_2(), "rule__EnumeratedClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getEnumeratedClassAccess().getEquivalentToAssignment_5_3_1(), "rule__EnumeratedClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getEnumeratedClassAccess().getDescribedByAssignment_6_2(), "rule__EnumeratedClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getEnumeratedClassAccess().getDescribedByAssignment_6_3_1(), "rule__EnumeratedClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getEnumeratedClassAccess().getOneOfAssignment_9(), "rule__EnumeratedClass__OneOfAssignment_9");
			builder.put(grammarAccess.getEnumeratedClassAccess().getOneOfAssignment_10_1(), "rule__EnumeratedClass__OneOfAssignment_10_1");
			builder.put(grammarAccess.getUnionClassAccess().getNameAssignment_1(), "rule__UnionClass__NameAssignment_1");
			builder.put(grammarAccess.getUnionClassAccess().getSubClassOfAssignment_3_2(), "rule__UnionClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getUnionClassAccess().getSubClassOfAssignment_3_3_1(), "rule__UnionClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getUnionClassAccess().getDisjointWithAssignment_4_2(), "rule__UnionClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getUnionClassAccess().getDisjointWithAssignment_4_3_1(), "rule__UnionClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getUnionClassAccess().getEquivalentToAssignment_5_2(), "rule__UnionClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getUnionClassAccess().getEquivalentToAssignment_5_3_1(), "rule__UnionClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getUnionClassAccess().getDescribedByAssignment_6_2(), "rule__UnionClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getUnionClassAccess().getDescribedByAssignment_6_3_1(), "rule__UnionClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getUnionClassAccess().getCombinationOfAssignment_9(), "rule__UnionClass__CombinationOfAssignment_9");
			builder.put(grammarAccess.getUnionClassAccess().getCombinationOfAssignment_10_1(), "rule__UnionClass__CombinationOfAssignment_10_1");
			builder.put(grammarAccess.getIntersectionClassAccess().getNameAssignment_1(), "rule__IntersectionClass__NameAssignment_1");
			builder.put(grammarAccess.getIntersectionClassAccess().getSubClassOfAssignment_3_2(), "rule__IntersectionClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getIntersectionClassAccess().getSubClassOfAssignment_3_3_1(), "rule__IntersectionClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getIntersectionClassAccess().getDisjointWithAssignment_4_2(), "rule__IntersectionClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getIntersectionClassAccess().getDisjointWithAssignment_4_3_1(), "rule__IntersectionClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getIntersectionClassAccess().getEquivalentToAssignment_5_2(), "rule__IntersectionClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getIntersectionClassAccess().getEquivalentToAssignment_5_3_1(), "rule__IntersectionClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getIntersectionClassAccess().getDescribedByAssignment_6_2(), "rule__IntersectionClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getIntersectionClassAccess().getDescribedByAssignment_6_3_1(), "rule__IntersectionClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getIntersectionClassAccess().getCombinationOfAssignment_9(), "rule__IntersectionClass__CombinationOfAssignment_9");
			builder.put(grammarAccess.getIntersectionClassAccess().getCombinationOfAssignment_10_1(), "rule__IntersectionClass__CombinationOfAssignment_10_1");
			builder.put(grammarAccess.getComplementClassAccess().getNameAssignment_1(), "rule__ComplementClass__NameAssignment_1");
			builder.put(grammarAccess.getComplementClassAccess().getSubClassOfAssignment_3_2(), "rule__ComplementClass__SubClassOfAssignment_3_2");
			builder.put(grammarAccess.getComplementClassAccess().getSubClassOfAssignment_3_3_1(), "rule__ComplementClass__SubClassOfAssignment_3_3_1");
			builder.put(grammarAccess.getComplementClassAccess().getDisjointWithAssignment_4_2(), "rule__ComplementClass__DisjointWithAssignment_4_2");
			builder.put(grammarAccess.getComplementClassAccess().getDisjointWithAssignment_4_3_1(), "rule__ComplementClass__DisjointWithAssignment_4_3_1");
			builder.put(grammarAccess.getComplementClassAccess().getEquivalentToAssignment_5_2(), "rule__ComplementClass__EquivalentToAssignment_5_2");
			builder.put(grammarAccess.getComplementClassAccess().getEquivalentToAssignment_5_3_1(), "rule__ComplementClass__EquivalentToAssignment_5_3_1");
			builder.put(grammarAccess.getComplementClassAccess().getDescribedByAssignment_6_2(), "rule__ComplementClass__DescribedByAssignment_6_2");
			builder.put(grammarAccess.getComplementClassAccess().getDescribedByAssignment_6_3_1(), "rule__ComplementClass__DescribedByAssignment_6_3_1");
			builder.put(grammarAccess.getComplementClassAccess().getCombinationOfAssignment_9(), "rule__ComplementClass__CombinationOfAssignment_9");
			builder.put(grammarAccess.getComplementClassAccess().getCombinationOfAssignment_10_1(), "rule__ComplementClass__CombinationOfAssignment_10_1");
			builder.put(grammarAccess.getSingleValueAccess().getNameAssignment_1(), "rule__SingleValue__NameAssignment_1");
			builder.put(grammarAccess.getSingleValueAccess().getIsOfTypeAssignment_4(), "rule__SingleValue__IsOfTypeAssignment_4");
			builder.put(grammarAccess.getSimplePropertyAccess().getIsFunctionalAssignment_1(), "rule__SimpleProperty__IsFunctionalAssignment_1");
			builder.put(grammarAccess.getSimplePropertyAccess().getIsSymmetricAssignment_2(), "rule__SimpleProperty__IsSymmetricAssignment_2");
			builder.put(grammarAccess.getSimplePropertyAccess().getIsTransitiveAssignment_3(), "rule__SimpleProperty__IsTransitiveAssignment_3");
			builder.put(grammarAccess.getSimplePropertyAccess().getIsInverseFunctionalAssignment_4(), "rule__SimpleProperty__IsInverseFunctionalAssignment_4");
			builder.put(grammarAccess.getSimplePropertyAccess().getNameAssignment_6(), "rule__SimpleProperty__NameAssignment_6");
			builder.put(grammarAccess.getSimplePropertyAccess().getRangeAssignment_8_1(), "rule__SimpleProperty__RangeAssignment_8_1");
			builder.put(grammarAccess.getSimplePropertyAccess().getSubPropertyOfAssignment_9_2(), "rule__SimpleProperty__SubPropertyOfAssignment_9_2");
			builder.put(grammarAccess.getSimplePropertyAccess().getSubPropertyOfAssignment_9_3_1(), "rule__SimpleProperty__SubPropertyOfAssignment_9_3_1");
			builder.put(grammarAccess.getSimplePropertyAccess().getEquivalentToAssignment_10_2(), "rule__SimpleProperty__EquivalentToAssignment_10_2");
			builder.put(grammarAccess.getSimplePropertyAccess().getEquivalentToAssignment_10_3_1(), "rule__SimpleProperty__EquivalentToAssignment_10_3_1");
			builder.put(grammarAccess.getSimplePropertyAccess().getInverseOfAssignment_11_2(), "rule__SimpleProperty__InverseOfAssignment_11_2");
			builder.put(grammarAccess.getSimplePropertyAccess().getInverseOfAssignment_11_3_1(), "rule__SimpleProperty__InverseOfAssignment_11_3_1");
			builder.put(grammarAccess.getSimplePropertyAccess().getDomainAssignment_12_1(), "rule__SimpleProperty__DomainAssignment_12_1");
			builder.put(grammarAccess.getConditionPropertyAccess().getIsFunctionalAssignment_1(), "rule__ConditionProperty__IsFunctionalAssignment_1");
			builder.put(grammarAccess.getConditionPropertyAccess().getIsSymmetricAssignment_2(), "rule__ConditionProperty__IsSymmetricAssignment_2");
			builder.put(grammarAccess.getConditionPropertyAccess().getIsTransitiveAssignment_3(), "rule__ConditionProperty__IsTransitiveAssignment_3");
			builder.put(grammarAccess.getConditionPropertyAccess().getIsInverseFunctionalAssignment_4(), "rule__ConditionProperty__IsInverseFunctionalAssignment_4");
			builder.put(grammarAccess.getConditionPropertyAccess().getNameAssignment_6(), "rule__ConditionProperty__NameAssignment_6");
			builder.put(grammarAccess.getConditionPropertyAccess().getRangeAssignment_8_1(), "rule__ConditionProperty__RangeAssignment_8_1");
			builder.put(grammarAccess.getConditionPropertyAccess().getSubPropertyOfAssignment_9_2(), "rule__ConditionProperty__SubPropertyOfAssignment_9_2");
			builder.put(grammarAccess.getConditionPropertyAccess().getSubPropertyOfAssignment_9_3_1(), "rule__ConditionProperty__SubPropertyOfAssignment_9_3_1");
			builder.put(grammarAccess.getConditionPropertyAccess().getEquivalentToAssignment_10_2(), "rule__ConditionProperty__EquivalentToAssignment_10_2");
			builder.put(grammarAccess.getConditionPropertyAccess().getEquivalentToAssignment_10_3_1(), "rule__ConditionProperty__EquivalentToAssignment_10_3_1");
			builder.put(grammarAccess.getConditionPropertyAccess().getInverseOfAssignment_11_2(), "rule__ConditionProperty__InverseOfAssignment_11_2");
			builder.put(grammarAccess.getConditionPropertyAccess().getInverseOfAssignment_11_3_1(), "rule__ConditionProperty__InverseOfAssignment_11_3_1");
			builder.put(grammarAccess.getConditionPropertyAccess().getDomainAssignment_12_1(), "rule__ConditionProperty__DomainAssignment_12_1");
			builder.put(grammarAccess.getDependentPropertyAccess().getIsFunctionalAssignment_0(), "rule__DependentProperty__IsFunctionalAssignment_0");
			builder.put(grammarAccess.getDependentPropertyAccess().getIsSymmetricAssignment_1(), "rule__DependentProperty__IsSymmetricAssignment_1");
			builder.put(grammarAccess.getDependentPropertyAccess().getIsTransitiveAssignment_2(), "rule__DependentProperty__IsTransitiveAssignment_2");
			builder.put(grammarAccess.getDependentPropertyAccess().getIsInverseFunctionalAssignment_3(), "rule__DependentProperty__IsInverseFunctionalAssignment_3");
			builder.put(grammarAccess.getDependentPropertyAccess().getNameAssignment_5(), "rule__DependentProperty__NameAssignment_5");
			builder.put(grammarAccess.getDependentPropertyAccess().getRangeAssignment_7_1(), "rule__DependentProperty__RangeAssignment_7_1");
			builder.put(grammarAccess.getDependentPropertyAccess().getSubPropertyOfAssignment_8_2(), "rule__DependentProperty__SubPropertyOfAssignment_8_2");
			builder.put(grammarAccess.getDependentPropertyAccess().getSubPropertyOfAssignment_8_3_1(), "rule__DependentProperty__SubPropertyOfAssignment_8_3_1");
			builder.put(grammarAccess.getDependentPropertyAccess().getEquivalentToAssignment_9_2(), "rule__DependentProperty__EquivalentToAssignment_9_2");
			builder.put(grammarAccess.getDependentPropertyAccess().getEquivalentToAssignment_9_3_1(), "rule__DependentProperty__EquivalentToAssignment_9_3_1");
			builder.put(grammarAccess.getDependentPropertyAccess().getInverseOfAssignment_10_2(), "rule__DependentProperty__InverseOfAssignment_10_2");
			builder.put(grammarAccess.getDependentPropertyAccess().getInverseOfAssignment_10_3_1(), "rule__DependentProperty__InverseOfAssignment_10_3_1");
			builder.put(grammarAccess.getDependentPropertyAccess().getDomainAssignment_11_1(), "rule__DependentProperty__DomainAssignment_11_1");
			builder.put(grammarAccess.getDependentPropertyAccess().getDependsOnAssignment_14(), "rule__DependentProperty__DependsOnAssignment_14");
			builder.put(grammarAccess.getDependentPropertyAccess().getDependsOnAssignment_15_1(), "rule__DependentProperty__DependsOnAssignment_15_1");
			builder.put(grammarAccess.getNotNumericTypeAccess().getNameAssignment_1(), "rule__NotNumericType__NameAssignment_1");
			builder.put(grammarAccess.getNotNumericTypeAccess().getBasedOnAssignment_4(), "rule__NotNumericType__BasedOnAssignment_4");
			builder.put(grammarAccess.getNumericType_ImplAccess().getNameAssignment_1(), "rule__NumericType_Impl__NameAssignment_1");
			builder.put(grammarAccess.getNumericType_ImplAccess().getBasedOnAssignment_4(), "rule__NumericType_Impl__BasedOnAssignment_4");
			builder.put(grammarAccess.getMeasureTypeAccess().getNameAssignment_1(), "rule__MeasureType__NameAssignment_1");
			builder.put(grammarAccess.getMeasureTypeAccess().getBasedOnAssignment_4(), "rule__MeasureType__BasedOnAssignment_4");
			builder.put(grammarAccess.getMeasureTypeAccess().getUnitAssignment_6(), "rule__MeasureType__UnitAssignment_6");
			builder.put(grammarAccess.getCurrencyTypeAccess().getNameAssignment_1(), "rule__CurrencyType__NameAssignment_1");
			builder.put(grammarAccess.getCurrencyTypeAccess().getBasedOnAssignment_4(), "rule__CurrencyType__BasedOnAssignment_4");
			builder.put(grammarAccess.getCurrencyTypeAccess().getCurrencyAssignment_6(), "rule__CurrencyType__CurrencyAssignment_6");
			builder.put(grammarAccess.getClassTypeAccess().getNameAssignment_1(), "rule__ClassType__NameAssignment_1");
			builder.put(grammarAccess.getClassTypeAccess().getBasedOnAssignment_4(), "rule__ClassType__BasedOnAssignment_4");
			builder.put(grammarAccess.getCollectionTypeAccess().getNameAssignment_1(), "rule__CollectionType__NameAssignment_1");
			builder.put(grammarAccess.getCollectionTypeAccess().getIsAssignment_4(), "rule__CollectionType__IsAssignment_4");
			builder.put(grammarAccess.getCollectionTypeAccess().getCollectionOfAssignment_6(), "rule__CollectionType__CollectionOfAssignment_6");
			builder.put(grammarAccess.getEnumeratedTypeAccess().getNameAssignment_1(), "rule__EnumeratedType__NameAssignment_1");
			builder.put(grammarAccess.getEnumeratedTypeAccess().getContainsAssignment_5(), "rule__EnumeratedType__ContainsAssignment_5");
			builder.put(grammarAccess.getEnumeratedTypeAccess().getContainsAssignment_6_1(), "rule__EnumeratedType__ContainsAssignment_6_1");
			builder.put(grammarAccess.getNumberEnumeratedTypeAccess().getNameAssignment_1(), "rule__NumberEnumeratedType__NameAssignment_1");
			builder.put(grammarAccess.getNumberEnumeratedTypeAccess().getContainsAssignment_5(), "rule__NumberEnumeratedType__ContainsAssignment_5");
			builder.put(grammarAccess.getNumberEnumeratedTypeAccess().getContainsAssignment_6_1(), "rule__NumberEnumeratedType__ContainsAssignment_6_1");
			builder.put(grammarAccess.getNamedUnit_ImplAccess().getExponentAssignment_3_1(), "rule__NamedUnit_Impl__ExponentAssignment_3_1");
			builder.put(grammarAccess.getDerivedUnitAccess().getDerivedUnitElementAssignment_4(), "rule__DerivedUnit__DerivedUnitElementAssignment_4");
			builder.put(grammarAccess.getDerivedUnitAccess().getDerivedUnitElementAssignment_5_1(), "rule__DerivedUnit__DerivedUnitElementAssignment_5_1");
			builder.put(grammarAccess.getNonStandardUnitAccess().getNameAssignment_2(), "rule__NonStandardUnit__NameAssignment_2");
			builder.put(grammarAccess.getNonStandardUnitAccess().getExponentAssignment_4_1(), "rule__NonStandardUnit__ExponentAssignment_4_1");
			builder.put(grammarAccess.getConversionBasedUnitAccess().getNameAssignment_1(), "rule__ConversionBasedUnit__NameAssignment_1");
			builder.put(grammarAccess.getConversionBasedUnitAccess().getExponentAssignment_3_1(), "rule__ConversionBasedUnit__ExponentAssignment_3_1");
			builder.put(grammarAccess.getConversionBasedUnitAccess().getValueComponentAssignment_5(), "rule__ConversionBasedUnit__ValueComponentAssignment_5");
			builder.put(grammarAccess.getConversionBasedUnitAccess().getUnitComponentAssignment_7(), "rule__ConversionBasedUnit__UnitComponentAssignment_7");
			builder.put(grammarAccess.getContextDependentUnitAccess().getNameAssignment_2(), "rule__ContextDependentUnit__NameAssignment_2");
			builder.put(grammarAccess.getContextDependentUnitAccess().getExponentAssignment_4_1(), "rule__ContextDependentUnit__ExponentAssignment_4_1");
			builder.put(grammarAccess.getStandardUnitAccess().getExponentAssignment_2_1(), "rule__StandardUnit__ExponentAssignment_2_1");
			builder.put(grammarAccess.getStandardUnitAccess().getPrefixAssignment_3_1(), "rule__StandardUnit__PrefixAssignment_3_1");
			builder.put(grammarAccess.getStandardUnitAccess().getNameAssignment_5(), "rule__StandardUnit__NameAssignment_5");
			builder.put(grammarAccess.getDerivedUnitElementAccess().getNameAssignment_1(), "rule__DerivedUnitElement__NameAssignment_1");
			builder.put(grammarAccess.getDerivedUnitElementAccess().getExponentAssignment_3_1(), "rule__DerivedUnitElement__ExponentAssignment_3_1");
			builder.put(grammarAccess.getDerivedUnitElementAccess().getUnitAssignment_5(), "rule__DerivedUnitElement__UnitAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DSLGrammarAccess grammarAccess;

	@Override
	protected InternalDSLParser createParser() {
		InternalDSLParser result = new InternalDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
